account/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    # path('login/', views.user_login, name='login'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', views.dashboard, name='dashboard'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(),  name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
    path('users/', views.user_list, name='user_list'),
    path('users/follow/', views.user_follow, name='user_follow'),
    path('users/<username>/', views.user_detail, name='user_detail'),
]

bookmarks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from . import views

app_name = 'images'

urlpatterns = [
    path('create/', views.image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/', views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
    path('', views.image_list, name='list'),
]

account/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.conf import settings

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(blank=True, upload_to='users/%Y/%m/%d')
    
    def __str__(self):
        return f'Perfil de {self.user.username}'
    
class Contact(models.Model):
    user_from = models.ForeignKey('auth.User',
                                  related_name ='rel_from_set',
                                  on_delete=models.CASCADE)
    user_to = models.ForeignKey('auth.User',
                                related_name='rel_to_set',
                                on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True,
                                   db_index=True)
    
    class Meta:
        ordering = ('-created',)
        
    def __str__(self):
        return f'{self.user_from} segue {self.user_to}'


# Add following field to User dynamically
user_model = get_user_model()
user_model.add_to_class('following',
                        models.ManyToManyField('self',
                                                through=Contact,
                                                related_name='followers',
                                                symmetrical=False))

account/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile

class LoginForm(forms.Form):
    username = forms.CharField(max_length=25)
    password = forms.CharField(widget=forms.PasswordInput)
    
class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Senha')
    password2 = forms.CharField(label='Repita a senha')
    
    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')
        
    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('As senhas são diferentes!')
        return cd['password2']
    
class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')
        
class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth', 'photo')

account/views.py
import re
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.contrib.auth import authenticate, login
from .forms import LoginForm, UserRegistrationForm
from django.contrib.auth.decorators import login_required
from .models import Profile, Contact
from .forms import LoginForm, UserRegistrationForm, UserEditForm, ProfileEditForm
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from django.views.decorators.http import require_POST
from common.decorators import ajax_required
from actions.utils import create_action
from actions.models import Action

# Create your views here.

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,
                                username=cd['username'],
                                password=cd['password'])

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Autenticado com sucesso')
                
                else:
                    return HttpResponse('Conta desativada')
            
            else:
                return HttpResponse('Login inválido')
    
    else:
        form = LoginForm()
        
    return render(request, 'account/login.html', {'form': form})

def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            Profile.objects.create(user=new_user)
            create_action(new_user, 'criou uma conta')
            return render(request, 'account/register_done.html', {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'account/register.html', {'user_form': user_form})

@login_required
def dashboard(request):
    actions = Action.objects.exclude(user=request.user)
    following_ids = request.user.following.values_list('id', flat=True)
    
    if following_ids:
        actions = actions.filter(user_id__in=following_ids)
    actions = actions.select_related('user', 'user__profile')\
                     .prefetch_related('target')[:10]
    
    return render(request,
                  'account/dashboard.html',
                  {'section': 'dashboard',
                   'actions': actions})
    
@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile, data=request.POST, files=request.FILES)
        
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Perfil atualizado com êxito.')
        
        else:
            messages.error(request, 'Um erro aconteceu ao tentarmos atualizar o seu perfil. Tente novamente.')
            
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    
    return render(request, 'account/edit.html', {'user_form': user_form,
                                                 'profile_form': profile_form})
    
    
@login_required
def user_list(request):
    users = User.objects.filter(is_active=True)
    return render(request,
                  'account/user/list.html',
                  {'section': 'people',
                   'users': users})

@login_required
def user_detail(request, username):
    user = get_object_or_404(User,
                             username=username,
                             is_active=True)
    return render(request,
                  'account/user/detail.html',
                  {'section': 'people',
                   'user': user})

@ajax_required
@require_POST
@login_required
def user_follow(request):
    user_id = request.POST.get('id')
    action = request.POST.get('action')
    if user_id and action:
        try:
            user = User.objects.get(id=user_id)
            if action == 'follow':
                Contact.objects.get_or_create(user_from=request.user, user_to=user)
                create_action(request.user, 'agora segue', user)
            else:
                Contact.objects.filter(user_from=request.user, user_to=user).delete()
            return JsonResponse({'status': 'ok'})
        except User.DoesNotExist:
            return JsonResponse({'status': 'error'})
    return JsonResponse({'status': 'error'})

account/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <style>
        @import url(//fonts.googleapis.com/css?family=Muli);

        body {
            margin:0;
            padding:0;
            font-family:helvetica, sans-serif;
        }

        p {
            line-height: 1.8;
        }

        a {
            color:#12c064;
            text-decoration:none;
        }

        a:hover {
            color:#00a74f;
        }

        h1, h2, h3, h4, h5 , h6 { font-family: 'Muli', sans-serif; font-weight:normal; }

        h1 {
            border-bottom:1px solid #bbb;
            padding:0 0 10px 0;
            margin:10px 0 20px 0;
        }

        h2 {
            margin:30px 0 20px;
        }

        ol {
            line-height:1.5;
        }

        #header {
            padding:10px 100px;
            font-size:14px;
            background:#12c064;
            color:#fff;
            border-bottom:4px solid #1cdf78;
            overflow:auto;
        }

        #header .logo {
            font-family: 'Muli', sans-serif;
            float:left;
            color:#f3f7cc;
            font-size:20px;
            margin-right:10%;
        }

        #header ul.menu {
            list-style:none;
            float:left;
            margin:0;
            padding:0;
        }
        #header ul.menu li {
            float:left;
            padding:4px 10px;
        }

        #header ul.menu li.selected a, #header ul.menu li.selected a:hover {
            color:#1b6d32;
            font-weight:bold;
        }

        #header a {
            color:#f3f7cc;
        }
        #header a:hover {
            color:#fff;
        }

        #header .user {
            float:right;
            padding-top:4px;
        }

        #content {
            padding:30px 100px;
        }

        /* forms */
        form {
            overflow:auto;
        }

        form p {
            width:100%;
            overflow:auto;
        }

        label {
            float:left;
            clear:both;
            color:#333;
            margin-bottom:4px;
        }
        input, textarea {
            clear:both;
            float:left;
            margin:0 0 10px;
            background:#efefef;
            border:0;
            padding:6px 10px;
            font-size:14px;
        }
        input[type=submit], a.button {
            font-weight:bold;
            background:#12c064;
            color:#fff;
            padding:10px 20px;
            font-size:14px;
            text-transform:uppercase;
        }
        .errorlist {
            color:#cc0033;
            float:left;
            clear:both;
            padding-left:10px;
        }
        .helptext {
            margin:0 0 20px 0;
            color:#aaa;
            clear:both;
            float:left;
            font-size:13px;
        }
        /* messages */
        ul.messages {
            margin:10px 100px;
            padding:0;
            list-style-type:
            none;
        }
        ul.messages li.success,
        ul.messages li.warning,
        ul.messages li.error,
        ul.messages li.info {
            margin:0;
            padding:14px 20px;
            list-style:none;
            color:#fff;
        }

        ul.messages li.success { background:#81ce81; }
        ul.messages li.success a { color:#0ac33e; }

        ul.messages li.error { background:#a30029; color:#e9828e; }
        ul.messages li.error a { color:#e9828e; }

        ul.messages li.info { background:#faffae; color:#696b4e; }
        ul.messages li.info a { color:#1586de; }

        ul.messages li.warning { background:#de9404; }
        ul.messages li.warning a { color:#f49000; }

        ul.messages li a.close {
            margin:0;
            float:right;
            opacity:1;
            border:0;
            box-shadow:none;
            text-shadow:none;
        }

        .login-form {
            float:left;
        }

        /* social-auth */
        .social {
            float:right;
        }
        .social li {
            list-style:none;
            padding:10px 20px;
            margin:0 0 10px 0;
        }
        .social li a {
            width:100%;
            height:100%;
            display:block;
            color:#fff;
        }
        .social li.facebook { background:#3b5399; }
        .social li.twitter { background:#00cffa; }
        .social li.google { background:#de1710; }


        /* images */

        .image-preview, .image-detail {
            max-width:300px;
            float:left;
            margin:0 20px 20px 0;
        }
        .image-detail { margin-top:20px; }
        .image-info div {
            padding:20px 0;
            overflow:auto;
        }
        .count {
            color:#aaa;
            border:3px solid #bbb;
            border-radius:26px;
            padding:10px 20px;
            margin:20px 10px 0;
        }
        a.like, a.follow { float:right; margin-top:-8px; }

        #image-list { overflow:auto; }
        #image-list .image {
            float:left;
            width:220px;
            height:300px;
            margin:0 10px 10px 10px;
            border-top:8px solid #12c064;
            background:#eee;
        }
        #image-list img { width:220px; height:220px; }
        #image-list .info { padding:10px; }
        #image-list .info a { color:#333; }
        .image-likes div {
            float:left;
            width:auto;
            padding:10px;
            text-align:center;
        }
        .image-likes img {
            width:120px;
            height:120px;
            border-radius:50%;
        }

        /* users */
        #people-list img {
            width:180px;
            height:180px;
            border-radius:50%;
            margin-bottom:20px;
        }
        #people-list .user {
            width:180px;
            float:left;
            overflow:auto;
            padding:10px;
        }
        #people-list .info { text-align:center; }
        img.user-detail {
            border-radius:50%;
            float:left;
        }
        .profile-info {
            float:left;
            overflow:auto;
            margin-right:20px;
        }
        .image-container { margin-top:40px; }

        /* actions */
        .action {
            clear:both;
            overflow:auto;
        }
        .action .images {
            float:left;
            margin:0 10px 10px 0;
        }
        .action .date {
            font-style:italic;
            color:#ccc;
        }
    </style>
</head>

<body>
    <div id="header">
        <span class="logo"><a href="https://feiquidoi.com:8000/account/">Feiquidoi</a></span>
        {% if request.user.is_authenticated %}
            <ul class="menu">
                <li {% if section == "dashboard" %}class="selected"{% endif %}>
                    <a href="{% url "dashboard" %}">Meu painel</a>
                </li>
                <li {% if section == "images" %}class="selected"{% endif %}>
                    <a href="{% url "images:list" %}">Imagens</a>
                </li>
                <li {% if section == "people" %}class="selected"{% endif %}>
                    <a href="{% url "user_list" %}">Pessoas</a>
                </li>
            </ul>
        {% endif %}

        <span class="user">
            {% if request.user.is_authenticated %}
                Olá, {{ user.first_name }}
                <a href="{% url "logout" %}">Deslogar</a>
            {% else %}
                <a href="{% url "login" %}">Login</a>
            {% endif %}
        </span>
    </div>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}">
                    {{ message|safe }}
                    <a href="#" class="close">x</a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2.2.1/src/js.cookie.min.js"></script>
    <script>
        var csrftoken = Cookies.get('csrftoken');
        function csrfSafeMethod(method) {
          return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $.ajaxSetup({
          beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
              xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
          }
        });
    
        $(document).ready(function(){
          {% block domready %}
          {% endblock %}
        });
      </script>
</body>

</html>